apiVersion: v1
kind: Namespace
metadata:
  name: siva-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flask-deploy
  namespace: siva-k8s
  labels: 
    app: python-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: frontend
  template: 
    metadata:
      name: pod2
      labels:
        app: frontend
    spec:
      containers:
      - name: c27
        image: us-south1-docker.pkg.dev/padma-489806/buildrepo/nginx:v1
        ports:
        - containerPort: 5000
